

version: '3.8'

services:
  web:
    build: ./web
    container_name: akici_web
    env_file: ./web/.env
    restart: unless-stopped
    expose:
      - '8000'
    volumes:
      - ./web:/app
    depends_on:
      - static
    networks:
      - webnet 

  static:
    image: nginx:stable-alpine
    container_name: akici_static
    volumes:
      - ./web/static:/usr/share/nginx/html:ro
    networks:
      - webnet

  proxy:
    image: nginx:stable-alpine
    container_name: akici_proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    networks:
      - webnet

networks:
  webnet:
    driver: bridge


  # Not: `static` servisi, statik dosyaları doğrudan Nginx'ten sunmak için eklenmiştir. `proxy` ise istemci trafiğini Gunicorn çalışan `web` servisine yönlendirir.
